# #Selling Partner API for FBA Inbound Eligibilty
#
# With the FBA Inbound Eligibility API, you can build applications that let sellers get eligibility previews for items before shipping them to Amazon's fulfillment centers. With this API you can find out if an item is eligible for inbound shipment to Amazon's fulfillment centers in a specific marketplace. You can also find out if an item is eligible for using the manufacturer barcode for FBA inventory tracking. Sellers can use this information to inform their decisions about which items to ship Amazon's fulfillment centers.
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

require 'date'

module AmznSpApi::FbaInboundEligibilityApiModel
  # The response object which contains the ASIN, marketplaceId if required, eligibility program, the eligibility status (boolean), and a list of ineligibility reason codes.
  class ItemEligibilityPreview
    # The ASIN for which eligibility was determined.
    attr_accessor :asin

    # The marketplace for which eligibility was determined.
    attr_accessor :marketplace_id

    # The program for which eligibility was determined.
    attr_accessor :program

    # Indicates if the item is eligible for the program.
    attr_accessor :is_eligible_for_program

    # Potential Ineligibility Reason Codes.
    attr_accessor :ineligibility_reason_list

    class EnumAttributeValidator
      attr_reader :datatype, :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'asin': :asin,
        'marketplace_id': :marketplaceId,
        'program': :program,
        'is_eligible_for_program': :isEligibleForProgram,
        'ineligibility_reason_list': :ineligibilityReasonList
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'asin': :Object,
        'marketplace_id': :Object,
        'program': :Object,
        'is_eligible_for_program': :Object,
        'ineligibility_reason_list': :Object
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      raise ArgumentError, 'The input argument (attributes) must be a hash in `AmznSpApi::FbaInboundEligibilityApiModel::ItemEligibilityPreview` initialize method' unless attributes.is_a?(Hash)

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        raise ArgumentError, "`#{k}` is not a valid attribute in `AmznSpApi::FbaInboundEligibilityApiModel::ItemEligibilityPreview`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect unless self.class.attribute_map.key?(k.to_sym)

        h[k.to_sym] = v
      end

      self.asin = attributes[:asin] if attributes.key?(:asin)

      self.marketplace_id = attributes[:marketplace_id] if attributes.key?(:marketplace_id)

      self.program = attributes[:program] if attributes.key?(:program)

      self.is_eligible_for_program = attributes[:is_eligible_for_program] if attributes.key?(:is_eligible_for_program)

      return unless attributes.key?(:ineligibility_reason_list)
      return unless (value = attributes[:ineligibility_reason_list]).is_a?(Array)

      self.ineligibility_reason_list = value
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = []
      invalid_properties.push('invalid value for "asin", asin cannot be nil.') if @asin.nil?

      invalid_properties.push('invalid value for "program", program cannot be nil.') if @program.nil?

      invalid_properties.push('invalid value for "is_eligible_for_program", is_eligible_for_program cannot be nil.') if @is_eligible_for_program.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @asin.nil?
      return false if @program.nil?

      program_validator = EnumAttributeValidator.new('Object', %w[INBOUND COMMINGLING])
      return false unless program_validator.valid?(@program)
      return false if @is_eligible_for_program.nil?

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] program Object to be assigned
    def program=(program)
      validator = EnumAttributeValidator.new('Object', %w[INBOUND COMMINGLING])
      raise ArgumentError, "invalid value for \"program\", must be one of #{validator.allowable_values}." unless validator.valid?(program)

      @program = program
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        asin == other.asin &&
        marketplace_id == other.marketplace_id &&
        program == other.program &&
        is_eligible_for_program == other.is_eligible_for_program &&
        ineligibility_reason_list == other.ineligibility_reason_list
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [asin, marketplace_id, program, is_eligible_for_program, ineligibility_reason_list].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize(::Regexp.last_match(1), v) }) if attributes[self.class.attribute_map[key]].is_a?(Array)
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmznSpApi::FbaInboundEligibilityApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end end
end
