# #Selling Partner API for Pricing
#
# The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, see the [Product Pricing v2022-05-01 Use Case Guide](doc:product-pricing-api-v2022-05-01-use-case-guide).
#
# OpenAPI spec version: 2022-05-01
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

module AmznSpApi::ProductPricingApiModel
  VERSION = '1.0.0'
end
