# #Selling Partner API for FBA Inventory
#
# The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

module AmznSpApi::FbaInventoryApiModel
  VERSION = '1.0.0'
end
