# #Selling Partner API for Authorization
#
# The Selling Partner API for Authorization helps developers manage authorizations and check the specific permissions associated with a given authorization.
#
# OpenAPI spec version: v1
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

# Common files
require 'authorization_api_model/api_client'
require 'authorization_api_model/api_error'
require 'authorization_api_model/version'
require 'authorization_api_model/configuration'

# Models
require 'authorization_api_model/models/authorization_code'
require 'authorization_api_model/models/error'
require 'authorization_api_model/models/error_list'
require 'authorization_api_model/models/get_authorization_code_response'

# APIs
require 'authorization_api_model/api/authorization_api'

module AmznSpApi::AuthorizationApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::AuthorizationApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
