=begin
#Selling Partner API for Easy Ship

#The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easy-ship-api-v2022-03-23-use-case-guide) for the differences in Easy Ship operations by marketplace.

OpenAPI spec version: 2022-03-23
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

# Common files
require 'easy_ship_model/api_client'
require 'easy_ship_model/api_error'
require 'easy_ship_model/version'
require 'easy_ship_model/configuration'

# Models
require 'easy_ship_model/models/amazon_order_id'
require 'easy_ship_model/models/code'
require 'easy_ship_model/models/create_scheduled_package_request'
require 'easy_ship_model/models/date_time'
require 'easy_ship_model/models/dimension'
require 'easy_ship_model/models/dimensions'
require 'easy_ship_model/models/error'
require 'easy_ship_model/models/error_list'
require 'easy_ship_model/models/handover_method'
require 'easy_ship_model/models/invoice_data'
require 'easy_ship_model/models/item'
require 'easy_ship_model/models/items'
require 'easy_ship_model/models/list_handover_slots_request'
require 'easy_ship_model/models/list_handover_slots_response'
require 'easy_ship_model/models/order_item_id'
require 'easy_ship_model/models/order_item_serial_number'
require 'easy_ship_model/models/order_item_serial_numbers'
require 'easy_ship_model/models/package'
require 'easy_ship_model/models/package_details'
require 'easy_ship_model/models/package_id'
require 'easy_ship_model/models/package_identifier'
require 'easy_ship_model/models/package_status'
require 'easy_ship_model/models/packages'
require 'easy_ship_model/models/scheduled_package_id'
require 'easy_ship_model/models/string'
require 'easy_ship_model/models/time_slot'
require 'easy_ship_model/models/time_slots'
require 'easy_ship_model/models/tracking_details'
require 'easy_ship_model/models/unit_of_length'
require 'easy_ship_model/models/unit_of_weight'
require 'easy_ship_model/models/update_package_details'
require 'easy_ship_model/models/update_package_details_list'
require 'easy_ship_model/models/update_scheduled_packages_request'
require 'easy_ship_model/models/weight'
require 'easy_ship_model/models/weight_value'

# APIs
require 'easy_ship_model/api/easy_ship_api'

module AmznSpApi::EasyShipModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::EasyShipModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
