=begin
#Selling Partner API for FBA Inventory

#The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

# Common files
require 'fba_inventory_api_model/api_client'
require 'fba_inventory_api_model/api_error'
require 'fba_inventory_api_model/version'
require 'fba_inventory_api_model/configuration'

# Models
require 'fba_inventory_api_model/models/error'
require 'fba_inventory_api_model/models/error_list'
require 'fba_inventory_api_model/models/get_inventory_summaries_response'
require 'fba_inventory_api_model/models/get_inventory_summaries_result'
require 'fba_inventory_api_model/models/granularity'
require 'fba_inventory_api_model/models/inventory_details'
require 'fba_inventory_api_model/models/inventory_summaries'
require 'fba_inventory_api_model/models/inventory_summary'
require 'fba_inventory_api_model/models/pagination'
require 'fba_inventory_api_model/models/researching_quantity'
require 'fba_inventory_api_model/models/researching_quantity_entry'
require 'fba_inventory_api_model/models/reserved_quantity'
require 'fba_inventory_api_model/models/unfulfillable_quantity'

# APIs
require 'fba_inventory_api_model/api/fba_inventory_api'

module AmznSpApi::FbaInventoryApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::FbaInventoryApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
