=begin
#Selling Partner API for Feeds

#The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.

OpenAPI spec version: 2021-06-30

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.36
=end

# Common files
require 'feeds_api_model/api_client'
require 'feeds_api_model/api_error'
require 'feeds_api_model/version'
require 'feeds_api_model/configuration'

# Models
require 'feeds_api_model/models/create_feed_document_response'
require 'feeds_api_model/models/create_feed_document_specification'
require 'feeds_api_model/models/create_feed_response'
require 'feeds_api_model/models/create_feed_specification'
require 'feeds_api_model/models/error'
require 'feeds_api_model/models/error_list'
require 'feeds_api_model/models/feed'
require 'feeds_api_model/models/feed_document'
require 'feeds_api_model/models/feed_list'
require 'feeds_api_model/models/feed_options'
require 'feeds_api_model/models/get_feeds_response'

# APIs
require 'feeds_api_model/api/feeds_api'

module AmznSpApi::FeedsApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::FeedsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
