=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

# Common files
require 'fulfillment_inbound_api_model/api_client'
require 'fulfillment_inbound_api_model/api_error'
require 'fulfillment_inbound_api_model/version'
require 'fulfillment_inbound_api_model/configuration'

# Models
require 'fulfillment_inbound_api_model/models/asin_inbound_guidance'
require 'fulfillment_inbound_api_model/models/asin_inbound_guidance_list'
require 'fulfillment_inbound_api_model/models/asin_prep_instructions'
require 'fulfillment_inbound_api_model/models/asin_prep_instructions_list'
require 'fulfillment_inbound_api_model/models/address'
require 'fulfillment_inbound_api_model/models/amazon_prep_fees_details'
require 'fulfillment_inbound_api_model/models/amazon_prep_fees_details_list'
require 'fulfillment_inbound_api_model/models/amount'
require 'fulfillment_inbound_api_model/models/barcode_instruction'
require 'fulfillment_inbound_api_model/models/big_decimal_type'
require 'fulfillment_inbound_api_model/models/bill_of_lading_download_url'
require 'fulfillment_inbound_api_model/models/box_contents_fee_details'
require 'fulfillment_inbound_api_model/models/box_contents_source'
require 'fulfillment_inbound_api_model/models/common_transport_result'
require 'fulfillment_inbound_api_model/models/condition'
require 'fulfillment_inbound_api_model/models/confirm_preorder_response'
require 'fulfillment_inbound_api_model/models/confirm_preorder_result'
require 'fulfillment_inbound_api_model/models/confirm_transport_response'
require 'fulfillment_inbound_api_model/models/contact'
require 'fulfillment_inbound_api_model/models/create_inbound_shipment_plan_request'
require 'fulfillment_inbound_api_model/models/create_inbound_shipment_plan_response'
require 'fulfillment_inbound_api_model/models/create_inbound_shipment_plan_result'
require 'fulfillment_inbound_api_model/models/currency_code'
require 'fulfillment_inbound_api_model/models/date_string_type'
require 'fulfillment_inbound_api_model/models/dimensions'
require 'fulfillment_inbound_api_model/models/error'
require 'fulfillment_inbound_api_model/models/error_list'
require 'fulfillment_inbound_api_model/models/error_reason'
require 'fulfillment_inbound_api_model/models/estimate_transport_response'
require 'fulfillment_inbound_api_model/models/get_bill_of_lading_response'
require 'fulfillment_inbound_api_model/models/get_inbound_guidance_response'
require 'fulfillment_inbound_api_model/models/get_inbound_guidance_result'
require 'fulfillment_inbound_api_model/models/get_labels_response'
require 'fulfillment_inbound_api_model/models/get_preorder_info_response'
require 'fulfillment_inbound_api_model/models/get_preorder_info_result'
require 'fulfillment_inbound_api_model/models/get_prep_instructions_response'
require 'fulfillment_inbound_api_model/models/get_prep_instructions_result'
require 'fulfillment_inbound_api_model/models/get_shipment_items_response'
require 'fulfillment_inbound_api_model/models/get_shipment_items_result'
require 'fulfillment_inbound_api_model/models/get_shipments_response'
require 'fulfillment_inbound_api_model/models/get_shipments_result'
require 'fulfillment_inbound_api_model/models/get_transport_details_response'
require 'fulfillment_inbound_api_model/models/get_transport_details_result'
require 'fulfillment_inbound_api_model/models/guidance_reason'
require 'fulfillment_inbound_api_model/models/guidance_reason_list'
require 'fulfillment_inbound_api_model/models/inbound_guidance'
require 'fulfillment_inbound_api_model/models/inbound_shipment_header'
require 'fulfillment_inbound_api_model/models/inbound_shipment_info'
require 'fulfillment_inbound_api_model/models/inbound_shipment_item'
require 'fulfillment_inbound_api_model/models/inbound_shipment_item_list'
require 'fulfillment_inbound_api_model/models/inbound_shipment_list'
require 'fulfillment_inbound_api_model/models/inbound_shipment_plan'
require 'fulfillment_inbound_api_model/models/inbound_shipment_plan_item'
require 'fulfillment_inbound_api_model/models/inbound_shipment_plan_item_list'
require 'fulfillment_inbound_api_model/models/inbound_shipment_plan_list'
require 'fulfillment_inbound_api_model/models/inbound_shipment_plan_request_item'
require 'fulfillment_inbound_api_model/models/inbound_shipment_plan_request_item_list'
require 'fulfillment_inbound_api_model/models/inbound_shipment_request'
require 'fulfillment_inbound_api_model/models/inbound_shipment_response'
require 'fulfillment_inbound_api_model/models/inbound_shipment_result'
require 'fulfillment_inbound_api_model/models/intended_box_contents_source'
require 'fulfillment_inbound_api_model/models/invalid_asin'
require 'fulfillment_inbound_api_model/models/invalid_asin_list'
require 'fulfillment_inbound_api_model/models/invalid_sku'
require 'fulfillment_inbound_api_model/models/invalid_sku_list'
require 'fulfillment_inbound_api_model/models/label_download_url'
require 'fulfillment_inbound_api_model/models/label_prep_preference'
require 'fulfillment_inbound_api_model/models/label_prep_type'
require 'fulfillment_inbound_api_model/models/non_partnered_ltl_data_input'
require 'fulfillment_inbound_api_model/models/non_partnered_ltl_data_output'
require 'fulfillment_inbound_api_model/models/non_partnered_small_parcel_data_input'
require 'fulfillment_inbound_api_model/models/non_partnered_small_parcel_data_output'
require 'fulfillment_inbound_api_model/models/non_partnered_small_parcel_package_input'
require 'fulfillment_inbound_api_model/models/non_partnered_small_parcel_package_input_list'
require 'fulfillment_inbound_api_model/models/non_partnered_small_parcel_package_output'
require 'fulfillment_inbound_api_model/models/non_partnered_small_parcel_package_output_list'
require 'fulfillment_inbound_api_model/models/package_status'
require 'fulfillment_inbound_api_model/models/pallet'
require 'fulfillment_inbound_api_model/models/pallet_list'
require 'fulfillment_inbound_api_model/models/partnered_estimate'
require 'fulfillment_inbound_api_model/models/partnered_ltl_data_input'
require 'fulfillment_inbound_api_model/models/partnered_ltl_data_output'
require 'fulfillment_inbound_api_model/models/partnered_small_parcel_data_input'
require 'fulfillment_inbound_api_model/models/partnered_small_parcel_data_output'
require 'fulfillment_inbound_api_model/models/partnered_small_parcel_package_input'
require 'fulfillment_inbound_api_model/models/partnered_small_parcel_package_input_list'
require 'fulfillment_inbound_api_model/models/partnered_small_parcel_package_output'
require 'fulfillment_inbound_api_model/models/partnered_small_parcel_package_output_list'
require 'fulfillment_inbound_api_model/models/prep_details'
require 'fulfillment_inbound_api_model/models/prep_details_list'
require 'fulfillment_inbound_api_model/models/prep_guidance'
require 'fulfillment_inbound_api_model/models/prep_instruction'
require 'fulfillment_inbound_api_model/models/prep_instruction_list'
require 'fulfillment_inbound_api_model/models/prep_owner'
require 'fulfillment_inbound_api_model/models/pro_number'
require 'fulfillment_inbound_api_model/models/put_transport_details_request'
require 'fulfillment_inbound_api_model/models/put_transport_details_response'
require 'fulfillment_inbound_api_model/models/quantity'
require 'fulfillment_inbound_api_model/models/sku_inbound_guidance'
require 'fulfillment_inbound_api_model/models/sku_inbound_guidance_list'
require 'fulfillment_inbound_api_model/models/sku_prep_instructions'
require 'fulfillment_inbound_api_model/models/sku_prep_instructions_list'
require 'fulfillment_inbound_api_model/models/seller_freight_class'
require 'fulfillment_inbound_api_model/models/shipment_status'
require 'fulfillment_inbound_api_model/models/shipment_type'
require 'fulfillment_inbound_api_model/models/time_stamp_string_type'
require 'fulfillment_inbound_api_model/models/tracking_id'
require 'fulfillment_inbound_api_model/models/transport_content'
require 'fulfillment_inbound_api_model/models/transport_detail_input'
require 'fulfillment_inbound_api_model/models/transport_detail_output'
require 'fulfillment_inbound_api_model/models/transport_header'
require 'fulfillment_inbound_api_model/models/transport_result'
require 'fulfillment_inbound_api_model/models/transport_status'
require 'fulfillment_inbound_api_model/models/unit_of_measurement'
require 'fulfillment_inbound_api_model/models/unit_of_weight'
require 'fulfillment_inbound_api_model/models/unsigned_int_type'
require 'fulfillment_inbound_api_model/models/void_transport_response'
require 'fulfillment_inbound_api_model/models/weight'

# APIs
require 'fulfillment_inbound_api_model/api/fba_inbound_api'

module AmznSpApi::FulfillmentInboundApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::FulfillmentInboundApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
