=begin
#Selling Partner API for Pricing

#The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

# Common files
require 'product_pricing_api_model/api_client'
require 'product_pricing_api_model/api_error'
require 'product_pricing_api_model/version'
require 'product_pricing_api_model/configuration'

# Models
require 'product_pricing_api_model/models/asin_identifier'
require 'product_pricing_api_model/models/attribute_set_list'
require 'product_pricing_api_model/models/buy_box_eligible_offers'
require 'product_pricing_api_model/models/buy_box_price_type'
require 'product_pricing_api_model/models/buy_box_prices'
require 'product_pricing_api_model/models/competitive_price_list'
require 'product_pricing_api_model/models/competitive_price_type'
require 'product_pricing_api_model/models/competitive_pricing_type'
require 'product_pricing_api_model/models/condition_type'
require 'product_pricing_api_model/models/detailed_shipping_time_type'
require 'product_pricing_api_model/models/error'
require 'product_pricing_api_model/models/error_list'
require 'product_pricing_api_model/models/fulfillment_channel_type'
require 'product_pricing_api_model/models/get_offers_response'
require 'product_pricing_api_model/models/get_offers_result'
require 'product_pricing_api_model/models/get_pricing_response'
require 'product_pricing_api_model/models/identifier_type'
require 'product_pricing_api_model/models/item_identifier'
require 'product_pricing_api_model/models/lowest_price_type'
require 'product_pricing_api_model/models/lowest_prices'
require 'product_pricing_api_model/models/money_type'
require 'product_pricing_api_model/models/number_of_offer_listings_list'
require 'product_pricing_api_model/models/number_of_offers'
require 'product_pricing_api_model/models/offer_count_type'
require 'product_pricing_api_model/models/offer_customer_type'
require 'product_pricing_api_model/models/offer_detail'
require 'product_pricing_api_model/models/offer_detail_list'
require 'product_pricing_api_model/models/offer_listing_count_type'
require 'product_pricing_api_model/models/offer_type'
require 'product_pricing_api_model/models/offers_list'
require 'product_pricing_api_model/models/points'
require 'product_pricing_api_model/models/price'
require 'product_pricing_api_model/models/price_list'
require 'product_pricing_api_model/models/price_type'
require 'product_pricing_api_model/models/prime_information_type'
require 'product_pricing_api_model/models/product'
require 'product_pricing_api_model/models/quantity_discount_price_type'
require 'product_pricing_api_model/models/quantity_discount_type'
require 'product_pricing_api_model/models/relationship_list'
require 'product_pricing_api_model/models/sales_rank_list'
require 'product_pricing_api_model/models/sales_rank_type'
require 'product_pricing_api_model/models/seller_feedback_type'
require 'product_pricing_api_model/models/seller_sku_identifier'
require 'product_pricing_api_model/models/ships_from_type'
require 'product_pricing_api_model/models/summary'

# APIs
require 'product_pricing_api_model/api/product_pricing_api'

module AmznSpApi::ProductPricingApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::ProductPricingApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
