# #Selling Partner API for Pricing
#
# The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, see the [Product Pricing v2022-05-01 Use Case Guide](doc:product-pricing-api-v2022-05-01-use-case-guide).
#
# OpenAPI spec version: 2022-05-01
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

# Common files
require 'product_pricing_api_model/api_client'
require 'product_pricing_api_model/api_error'
require 'product_pricing_api_model/version'
require 'product_pricing_api_model/configuration'

# Models
require 'product_pricing_api_model/models/asin'
require 'product_pricing_api_model/models/batch_request'
require 'product_pricing_api_model/models/batch_response'
require 'product_pricing_api_model/models/condition'
require 'product_pricing_api_model/models/error'
require 'product_pricing_api_model/models/error_list'
require 'product_pricing_api_model/models/errors'
require 'product_pricing_api_model/models/featured_offer'
require 'product_pricing_api_model/models/featured_offer_expected_price'
require 'product_pricing_api_model/models/featured_offer_expected_price_request'
require 'product_pricing_api_model/models/featured_offer_expected_price_request_list'
require 'product_pricing_api_model/models/featured_offer_expected_price_request_params'
require 'product_pricing_api_model/models/featured_offer_expected_price_response'
require 'product_pricing_api_model/models/featured_offer_expected_price_response_body'
require 'product_pricing_api_model/models/featured_offer_expected_price_response_list'
require 'product_pricing_api_model/models/featured_offer_expected_price_result'
require 'product_pricing_api_model/models/featured_offer_expected_price_result_list'
require 'product_pricing_api_model/models/fulfillment_type'
require 'product_pricing_api_model/models/get_featured_offer_expected_price_batch_request'
require 'product_pricing_api_model/models/get_featured_offer_expected_price_batch_response'
require 'product_pricing_api_model/models/http_body'
require 'product_pricing_api_model/models/http_headers'
require 'product_pricing_api_model/models/http_method'
require 'product_pricing_api_model/models/http_status_line'
require 'product_pricing_api_model/models/marketplace_id'
require 'product_pricing_api_model/models/money_type'
require 'product_pricing_api_model/models/offer_identifier'
require 'product_pricing_api_model/models/points'
require 'product_pricing_api_model/models/price'
require 'product_pricing_api_model/models/sku'

# APIs
require 'product_pricing_api_model/api/product_pricing_api'

module AmznSpApi::ProductPricingApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::ProductPricingApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
