=begin
#Selling Partner API for Sellers

#The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.36
=end

# Common files
require 'sellers_api_model/api_client'
require 'sellers_api_model/api_error'
require 'sellers_api_model/version'
require 'sellers_api_model/configuration'

# Models
require 'sellers_api_model/models/error'
require 'sellers_api_model/models/error_list'
require 'sellers_api_model/models/get_marketplace_participations_response'
require 'sellers_api_model/models/marketplace'
require 'sellers_api_model/models/marketplace_participation'
require 'sellers_api_model/models/marketplace_participation_list'
require 'sellers_api_model/models/participation'

# APIs
require 'sellers_api_model/api/sellers_api'

module AmznSpApi::SellersApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::SellersApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
