=begin
#Selling Partner API for Solicitations

#With the Solicitations API you can build applications that send non-critical solicitations to buyers. You can get a list of solicitation types that are available for an order that you specify, then call an operation that sends a solicitation to the buyer for that order. Buyers cannot respond to solicitations sent by this API, and these solicitations do not appear in the Messaging section of Seller Central or in the recipient's Message Center. The Solicitations API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.36
=end

# Common files
require 'solicitations_api_model/api_client'
require 'solicitations_api_model/api_error'
require 'solicitations_api_model/version'
require 'solicitations_api_model/configuration'

# Models
require 'solicitations_api_model/models/create_product_review_and_seller_feedback_solicitation_response'
require 'solicitations_api_model/models/error'
require 'solicitations_api_model/models/error_list'
require 'solicitations_api_model/models/get_schema_response'
require 'solicitations_api_model/models/get_schema_response__links'
require 'solicitations_api_model/models/get_solicitation_action_response'
require 'solicitations_api_model/models/get_solicitation_action_response__embedded'
require 'solicitations_api_model/models/get_solicitation_action_response__links'
require 'solicitations_api_model/models/get_solicitation_actions_for_order_response'
require 'solicitations_api_model/models/get_solicitation_actions_for_order_response__embedded'
require 'solicitations_api_model/models/get_solicitation_actions_for_order_response__links'
require 'solicitations_api_model/models/link_object'
require 'solicitations_api_model/models/schema'
require 'solicitations_api_model/models/solicitations_action'

# APIs
require 'solicitations_api_model/api/solicitations_api'

module AmznSpApi::SolicitationsApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmznSpApi::SolicitationsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
