# #Selling Partner API for Finances
#
# The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
#
# OpenAPI spec version: v0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

require 'date'

module AmznSpApi::FinancesApiModel
  # An event related to the seller's Pay with Amazon account.
  class PayWithAmazonEvent
    # An order identifier that is specified by the seller.
    attr_accessor :seller_order_id

    attr_accessor :transaction_posted_date, :charge, :fee_list

    # The type of business object.
    attr_accessor :business_object_type

    # The sales channel for the transaction.
    attr_accessor :sales_channel

    # The type of payment.  Possible values:  * Sales
    attr_accessor :payment_amount_type

    # A short description of this payment event.
    attr_accessor :amount_description

    # The fulfillment channel.  Possible values:  * AFN - Amazon Fulfillment Network (Fulfillment by Amazon)  * MFN - Merchant Fulfillment Network (self-fulfilled)
    attr_accessor :fulfillment_channel

    # The store name where the event occurred.
    attr_accessor :store_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'seller_order_id': :SellerOrderId,
        'transaction_posted_date': :TransactionPostedDate,
        'business_object_type': :BusinessObjectType,
        'sales_channel': :SalesChannel,
        'charge': :Charge,
        'fee_list': :FeeList,
        'payment_amount_type': :PaymentAmountType,
        'amount_description': :AmountDescription,
        'fulfillment_channel': :FulfillmentChannel,
        'store_name': :StoreName
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'seller_order_id': :Object,
        'transaction_posted_date': :Object,
        'business_object_type': :Object,
        'sales_channel': :Object,
        'charge': :Object,
        'fee_list': :Object,
        'payment_amount_type': :Object,
        'amount_description': :Object,
        'fulfillment_channel': :Object,
        'store_name': :Object
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      raise ArgumentError, 'The input argument (attributes) must be a hash in `AmznSpApi::FinancesApiModel::PayWithAmazonEvent` initialize method' unless attributes.is_a?(Hash)

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        raise ArgumentError, "`#{k}` is not a valid attribute in `AmznSpApi::FinancesApiModel::PayWithAmazonEvent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect unless self.class.attribute_map.key?(k.to_sym)

        h[k.to_sym] = v
      end

      self.seller_order_id = attributes[:seller_order_id] if attributes.key?(:seller_order_id)

      self.transaction_posted_date = attributes[:transaction_posted_date] if attributes.key?(:transaction_posted_date)

      self.business_object_type = attributes[:business_object_type] if attributes.key?(:business_object_type)

      self.sales_channel = attributes[:sales_channel] if attributes.key?(:sales_channel)

      self.charge = attributes[:charge] if attributes.key?(:charge)

      self.fee_list = attributes[:fee_list] if attributes.key?(:fee_list)

      self.payment_amount_type = attributes[:payment_amount_type] if attributes.key?(:payment_amount_type)

      self.amount_description = attributes[:amount_description] if attributes.key?(:amount_description)

      self.fulfillment_channel = attributes[:fulfillment_channel] if attributes.key?(:fulfillment_channel)

      return unless attributes.key?(:store_name)

      self.store_name = attributes[:store_name]
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      []
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        seller_order_id == other.seller_order_id &&
        transaction_posted_date == other.transaction_posted_date &&
        business_object_type == other.business_object_type &&
        sales_channel == other.sales_channel &&
        charge == other.charge &&
        fee_list == other.fee_list &&
        payment_amount_type == other.payment_amount_type &&
        amount_description == other.amount_description &&
        fulfillment_channel == other.fulfillment_channel &&
        store_name == other.store_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [seller_order_id, transaction_posted_date, business_object_type, sales_channel, charge, fee_list, payment_amount_type, amount_description, fulfillment_channel, store_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize(::Regexp.last_match(1), v) }) if attributes[self.class.attribute_map[key]].is_a?(Array)
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmznSpApi::FinancesApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end end
end
