# #Selling Partner API for Orders
#
# The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
#
# OpenAPI spec version: v0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 3.0.36

require 'date'

module AmznSpApi::OrdersApiModel
  # A single order item.
  class OrderItem
    # The Amazon Standard Identification Number (ASIN) of the item.
    attr_accessor :asin

    # The seller stock keeping unit (SKU) of the item.
    attr_accessor :seller_sku

    # An Amazon-defined order item identifier.
    attr_accessor :order_item_id

    # The name of the item.
    attr_accessor :title

    # The number of items in the order.
    attr_accessor :quantity_ordered

    # The number of items shipped.
    attr_accessor :quantity_shipped

    attr_accessor :product_info, :points_granted, :item_price, :shipping_price, :item_tax, :shipping_tax, :shipping_discount, :shipping_discount_tax, :promotion_discount, :promotion_discount_tax, :promotion_ids, :cod_fee, :cod_fee_discount, :tax_collection, :buyer_info, :buyer_requested_cancel, :item_approval_context

    # When true, the item is a gift.
    attr_accessor :is_gift

    # The condition of the item as described by the seller.
    attr_accessor :condition_note

    # The condition of the item.  Possible values: New, Used, Collectible, Refurbished, Preorder, Club.
    attr_accessor :condition_id

    # The subcondition of the item.  Possible values: New, Mint, Very Good, Good, Acceptable, Poor, Club, OEM, Warranty, Refurbished Warranty, Refurbished, Open Box, Any, Other.
    attr_accessor :condition_subtype_id

    # The start date of the scheduled delivery window in the time zone of the order destination. In ISO 8601 date time format.
    attr_accessor :scheduled_delivery_start_date

    # The end date of the scheduled delivery window in the time zone of the order destination. In ISO 8601 date time format.
    attr_accessor :scheduled_delivery_end_date

    # Indicates that the selling price is a special price that is available only for Amazon Business orders. For more information about the Amazon Business Seller Program, see the [Amazon Business website](https://www.amazon.com/b2b/info/amazon-business).   Possible values: BusinessPrice - A special price that is available only for Amazon Business orders.
    attr_accessor :price_designation

    # When true, the product type for this item has a serial number.  Returned only for Amazon Easy Ship orders.
    attr_accessor :serial_number_required

    # When true, transparency codes are required.
    attr_accessor :is_transparency

    # The IOSS number for the marketplace. Sellers shipping to the European Union (EU) from outside of the EU must provide this IOSS number to their carrier when Amazon has collected the VAT on the sale.
    attr_accessor :ioss_number

    # The store chain store identifier. Linked to a specific store in a store chain.
    attr_accessor :store_chain_store_id

    # The category of deemed reseller. This applies to selling partners that are not based in the EU and is used to help them meet the VAT Deemed Reseller tax laws in the EU and UK.
    attr_accessor :deemed_reseller_category

    # A list of serial numbers for electronic products that are shipped to customers. Returned for FBA orders only.
    attr_accessor :serial_numbers

    class EnumAttributeValidator
      attr_reader :datatype, :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'asin': :ASIN,
        'seller_sku': :SellerSKU,
        'order_item_id': :OrderItemId,
        'title': :Title,
        'quantity_ordered': :QuantityOrdered,
        'quantity_shipped': :QuantityShipped,
        'product_info': :ProductInfo,
        'points_granted': :PointsGranted,
        'item_price': :ItemPrice,
        'shipping_price': :ShippingPrice,
        'item_tax': :ItemTax,
        'shipping_tax': :ShippingTax,
        'shipping_discount': :ShippingDiscount,
        'shipping_discount_tax': :ShippingDiscountTax,
        'promotion_discount': :PromotionDiscount,
        'promotion_discount_tax': :PromotionDiscountTax,
        'promotion_ids': :PromotionIds,
        'cod_fee': :CODFee,
        'cod_fee_discount': :CODFeeDiscount,
        'is_gift': :IsGift,
        'condition_note': :ConditionNote,
        'condition_id': :ConditionId,
        'condition_subtype_id': :ConditionSubtypeId,
        'scheduled_delivery_start_date': :ScheduledDeliveryStartDate,
        'scheduled_delivery_end_date': :ScheduledDeliveryEndDate,
        'price_designation': :PriceDesignation,
        'tax_collection': :TaxCollection,
        'serial_number_required': :SerialNumberRequired,
        'is_transparency': :IsTransparency,
        'ioss_number': :IossNumber,
        'store_chain_store_id': :StoreChainStoreId,
        'deemed_reseller_category': :DeemedResellerCategory,
        'buyer_info': :BuyerInfo,
        'buyer_requested_cancel': :BuyerRequestedCancel,
        'item_approval_context': :ItemApprovalContext,
        'serial_numbers': :SerialNumbers
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'asin': :Object,
        'seller_sku': :Object,
        'order_item_id': :Object,
        'title': :Object,
        'quantity_ordered': :Object,
        'quantity_shipped': :Object,
        'product_info': :Object,
        'points_granted': :Object,
        'item_price': :Object,
        'shipping_price': :Object,
        'item_tax': :Object,
        'shipping_tax': :Object,
        'shipping_discount': :Object,
        'shipping_discount_tax': :Object,
        'promotion_discount': :Object,
        'promotion_discount_tax': :Object,
        'promotion_ids': :Object,
        'cod_fee': :Object,
        'cod_fee_discount': :Object,
        'is_gift': :Object,
        'condition_note': :Object,
        'condition_id': :Object,
        'condition_subtype_id': :Object,
        'scheduled_delivery_start_date': :Object,
        'scheduled_delivery_end_date': :Object,
        'price_designation': :Object,
        'tax_collection': :Object,
        'serial_number_required': :Object,
        'is_transparency': :Object,
        'ioss_number': :Object,
        'store_chain_store_id': :Object,
        'deemed_reseller_category': :Object,
        'buyer_info': :Object,
        'buyer_requested_cancel': :Object,
        'item_approval_context': :Object,
        'serial_numbers': :Object
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      raise ArgumentError, 'The input argument (attributes) must be a hash in `AmznSpApi::OrdersApiModel::OrderItem` initialize method' unless attributes.is_a?(Hash)

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        raise ArgumentError, "`#{k}` is not a valid attribute in `AmznSpApi::OrdersApiModel::OrderItem`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect unless self.class.attribute_map.key?(k.to_sym)

        h[k.to_sym] = v
      end

      self.asin = attributes[:asin] if attributes.key?(:asin)

      self.seller_sku = attributes[:seller_sku] if attributes.key?(:seller_sku)

      self.order_item_id = attributes[:order_item_id] if attributes.key?(:order_item_id)

      self.title = attributes[:title] if attributes.key?(:title)

      self.quantity_ordered = attributes[:quantity_ordered] if attributes.key?(:quantity_ordered)

      self.quantity_shipped = attributes[:quantity_shipped] if attributes.key?(:quantity_shipped)

      self.product_info = attributes[:product_info] if attributes.key?(:product_info)

      self.points_granted = attributes[:points_granted] if attributes.key?(:points_granted)

      self.item_price = attributes[:item_price] if attributes.key?(:item_price)

      self.shipping_price = attributes[:shipping_price] if attributes.key?(:shipping_price)

      self.item_tax = attributes[:item_tax] if attributes.key?(:item_tax)

      self.shipping_tax = attributes[:shipping_tax] if attributes.key?(:shipping_tax)

      self.shipping_discount = attributes[:shipping_discount] if attributes.key?(:shipping_discount)

      self.shipping_discount_tax = attributes[:shipping_discount_tax] if attributes.key?(:shipping_discount_tax)

      self.promotion_discount = attributes[:promotion_discount] if attributes.key?(:promotion_discount)

      self.promotion_discount_tax = attributes[:promotion_discount_tax] if attributes.key?(:promotion_discount_tax)

      self.promotion_ids = attributes[:promotion_ids] if attributes.key?(:promotion_ids)

      self.cod_fee = attributes[:cod_fee] if attributes.key?(:cod_fee)

      self.cod_fee_discount = attributes[:cod_fee_discount] if attributes.key?(:cod_fee_discount)

      self.is_gift = attributes[:is_gift] if attributes.key?(:is_gift)

      self.condition_note = attributes[:condition_note] if attributes.key?(:condition_note)

      self.condition_id = attributes[:condition_id] if attributes.key?(:condition_id)

      self.condition_subtype_id = attributes[:condition_subtype_id] if attributes.key?(:condition_subtype_id)

      self.scheduled_delivery_start_date = attributes[:scheduled_delivery_start_date] if attributes.key?(:scheduled_delivery_start_date)

      self.scheduled_delivery_end_date = attributes[:scheduled_delivery_end_date] if attributes.key?(:scheduled_delivery_end_date)

      self.price_designation = attributes[:price_designation] if attributes.key?(:price_designation)

      self.tax_collection = attributes[:tax_collection] if attributes.key?(:tax_collection)

      self.serial_number_required = attributes[:serial_number_required] if attributes.key?(:serial_number_required)

      self.is_transparency = attributes[:is_transparency] if attributes.key?(:is_transparency)

      self.ioss_number = attributes[:ioss_number] if attributes.key?(:ioss_number)

      self.store_chain_store_id = attributes[:store_chain_store_id] if attributes.key?(:store_chain_store_id)

      self.deemed_reseller_category = attributes[:deemed_reseller_category] if attributes.key?(:deemed_reseller_category)

      self.buyer_info = attributes[:buyer_info] if attributes.key?(:buyer_info)

      self.buyer_requested_cancel = attributes[:buyer_requested_cancel] if attributes.key?(:buyer_requested_cancel)

      self.item_approval_context = attributes[:item_approval_context] if attributes.key?(:item_approval_context)

      return unless attributes.key?(:serial_numbers)
      return unless (value = attributes[:serial_numbers]).is_a?(Array)

      self.serial_numbers = value
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = []
      invalid_properties.push('invalid value for "asin", asin cannot be nil.') if @asin.nil?

      invalid_properties.push('invalid value for "order_item_id", order_item_id cannot be nil.') if @order_item_id.nil?

      invalid_properties.push('invalid value for "quantity_ordered", quantity_ordered cannot be nil.') if @quantity_ordered.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @asin.nil?
      return false if @order_item_id.nil?
      return false if @quantity_ordered.nil?

      deemed_reseller_category_validator = EnumAttributeValidator.new('Object', %w[IOSS UOSS])
      return false unless deemed_reseller_category_validator.valid?(@deemed_reseller_category)

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] deemed_reseller_category Object to be assigned
    def deemed_reseller_category=(deemed_reseller_category)
      validator = EnumAttributeValidator.new('Object', %w[IOSS UOSS])
      raise ArgumentError, "invalid value for \"deemed_reseller_category\", must be one of #{validator.allowable_values}." unless validator.valid?(deemed_reseller_category)

      @deemed_reseller_category = deemed_reseller_category
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        asin == other.asin &&
        seller_sku == other.seller_sku &&
        order_item_id == other.order_item_id &&
        title == other.title &&
        quantity_ordered == other.quantity_ordered &&
        quantity_shipped == other.quantity_shipped &&
        product_info == other.product_info &&
        points_granted == other.points_granted &&
        item_price == other.item_price &&
        shipping_price == other.shipping_price &&
        item_tax == other.item_tax &&
        shipping_tax == other.shipping_tax &&
        shipping_discount == other.shipping_discount &&
        shipping_discount_tax == other.shipping_discount_tax &&
        promotion_discount == other.promotion_discount &&
        promotion_discount_tax == other.promotion_discount_tax &&
        promotion_ids == other.promotion_ids &&
        cod_fee == other.cod_fee &&
        cod_fee_discount == other.cod_fee_discount &&
        is_gift == other.is_gift &&
        condition_note == other.condition_note &&
        condition_id == other.condition_id &&
        condition_subtype_id == other.condition_subtype_id &&
        scheduled_delivery_start_date == other.scheduled_delivery_start_date &&
        scheduled_delivery_end_date == other.scheduled_delivery_end_date &&
        price_designation == other.price_designation &&
        tax_collection == other.tax_collection &&
        serial_number_required == other.serial_number_required &&
        is_transparency == other.is_transparency &&
        ioss_number == other.ioss_number &&
        store_chain_store_id == other.store_chain_store_id &&
        deemed_reseller_category == other.deemed_reseller_category &&
        buyer_info == other.buyer_info &&
        buyer_requested_cancel == other.buyer_requested_cancel &&
        item_approval_context == other.item_approval_context &&
        serial_numbers == other.serial_numbers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [asin, seller_sku, order_item_id, title, quantity_ordered, quantity_shipped, product_info, points_granted, item_price, shipping_price, item_tax, shipping_tax, shipping_discount, shipping_discount_tax, promotion_discount, promotion_discount_tax, promotion_ids, cod_fee, cod_fee_discount, is_gift, condition_note, condition_id, condition_subtype_id, scheduled_delivery_start_date, scheduled_delivery_end_date, price_designation, tax_collection, serial_number_required, is_transparency, ioss_number, store_chain_store_id, deemed_reseller_category, buyer_info, buyer_requested_cancel, item_approval_context, serial_numbers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize(::Regexp.last_match(1), v) }) if attributes[self.class.attribute_map[key]].is_a?(Array)
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmznSpApi::OrdersApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end end
end
